### PR TITLE
Re-organize the repository's directories and clean up unnecessary binary files.

### PR DESCRIPTION
**Pull request by nikheizen**
When downloading source code from github, I do not expect to recieve compiled binaries, project files, or system-specific hidden files.

Adding a .gitignore, removing the compiled binaries and project files from the source, and changing the repository architecture to not contain a redundant top-level "Sil" directory makes the whole thing look a lot cleaner.

I also moved the .txt files in (what is now) the root directory to .md format with names that github.com recognizes, so that the compilation information will show up on the front page of the repo. The manual is still the de facto readme, of course.

### CODE REVIEW

**Comment by sil-quirk** [comment]
With regard to project files in general, incidentally, if I were downloading a project from GitHub that supported compilation with Visual Studio, I would most certainly expect to have project files included. I am less certain of the situation with XCode.

**Comment by sil-quirk** [comment]
Having reflected a little further, I'm disposed to trim support and Makefiles back to the minimum until someone wants to help support a new platform. Asking will only encourage that one guy who is thinking of getting a Mac next year. If you restore the silx script I think I can approve a merge.

**Comment by nikheizen** [comment]
You are right about the project files belonging in the repository. So I've brought them back.
I restored the silx script and rebased over current master.

**Comment by sil-quirk** [comment]
I think it will be clearest to do this as two steps - one, reorganise directory structure and dispose of all that mess; two, look at dropping support for unused platforms. This pull request does the first step so I'll merge as is and then consider the second.

**Pull request merged**
