### PR TITLE
Reduce references to slavery

### PR DESCRIPTION
**Pull request by RojjaCebolla**
For some folks, random slaves lying around the dungeon can feel a little
jarring. Replace them with prisoners lying around instead.

Not meaningfully changed: slave quest

### CODE REVIEW

**Comment by sil-quirk** [comment]
Morgoth's slaves / thralls are very much part of the source material, so I fail to understand the "feels jarring" comment. Could you expand?

**Comment by Zireael07** [comment]
I strongly suspect this is a cultural issue or someone feels "triggered" by the fact there is slavery in this fictional universe.

**Comment by RojjaCebolla** [comment]
> Morgoth's slaves / thralls are very much part of the source material, so I fail to understand the "feels jarring" comment. Could you expand?

Ah, I'm not a tolkien aficionado, just a fan of roguelikes. So coming from other roguelikes, it just felt a little gratuitous. But it sounds like this is part of a source material that the game is based on.

**Comment by sil-quirk** [comment]
Yeah, it's very much part of the sources; literally the first Google hit for Angband (https://lotr.fandom.com/wiki/Angband) mentions the slave quarters and there are many references in Tolkien to this; to pick two of the most notable, Morgoth is called "craven, and lord of slaves" when Fingolfin challenges him, and his slaves are ultimately freed when he is overthrown by the Valar.

"Thrall" is used often and interchangeably with slave - Tolkien drew heavily on Old English and Norse mythos - so I would be open to rebranding them as thralls, but fewer people know the word.

**Comment by Zireael07** [comment]
'Thrall' is actually pretty common in fantasy/rpg circles and makes it immediately clear that this is not real-world slaves. So a +1 to renaming.

**Pull request closed without merging**
